=== JMARRUJO91/jazmyne/NCRTestDescr.dtd
<?xml encoding="UTF-8"?>

<!-- Revision: 1.0.0 NCRTestDescr.dtd -->

<!ELEMENT NCRTestDescr (Test+)>

<!ELEMENT Test (Desc, Params, Results)>
<!ATTLIST Test
          number CDATA #REQUIRED
          attended (yes | no) #REQUIRED
          destructive (yes | no) #REQUIRED
          exclusiveAccess (yes | no) #REQUIRED>
          
<!ELEMENT Desc (#PCDATA)>
          
<!ELEMENT Params (Param*)>
<!ATTLIST Params
          separator CDATA #REQUIRED>

<!ELEMENT Param (Desc, UIPrompt)>
<!ATTLIST Param
          paramType (string | integer) #REQUIRED
          defaultValue CDATA #IMPLIED
          isTimeout (yes | no) #IMPLIED>

<!ELEMENT UIPrompt (#PCDATA)>

<!ELEMENT Results (Result+)>
<!ATTLIST Results
          separator CDATA #REQUIRED>

<!ELEMENT Result (Desc)>

=== JMARRUJO91/jazmyne/NCRCashDrawerTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<NCRTestDescr>

<!--******************** Test 1: Open cash drawer ******************** -->
<Test number="1" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Open cash drawer</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--****************** Test 2: Get last drawer status ******************* -->
<Test number="2" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get last drawer status</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Drawer status</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRICM330DIPMSRTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRMSRModel.       *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Get Part Number ****************** -->
<Test number="1" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Get MSR Part Number</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
        <Result><Desc>MSR Part Number</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: Read MSR Card ******************** -->
<Test number="2" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Read MSR Card</Desc>
    <Params separator=",">
        <Param paramType="integer" defaultValue="15000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
        <Result><Desc>Length of track 1 data</Desc></Result>
        <Result><Desc>Track 1 data</Desc></Result>
        <Result><Desc>Length of track 2 data</Desc></Result>
        <Result><Desc>Track 2 data</Desc></Result>
        <Result><Desc>Length of track 3 data</Desc></Result>
        <Result><Desc>Track 3 data</Desc></Result>
        <Result><Desc>Length of track 4 data</Desc></Result>
        <Result><Desc>Track 4 data</Desc></Result>
    </Results>
</Test>

<!--*************************************************************** -->
<!--**************** ICM 330 DIP MSR Specific Tests *************** -->
<!--*************************************************************** -->

<!--******************** Test 3: Get CCL Data ********************* -->
<Test number="3" attended="yes" destructive="no" exclusiveAccess="yes">
    <Desc>Get CCL Data</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
        <Result><Desc>Serial Number</Desc></Result>
        <Result><Desc>Supervisor Area Firmware Version</Desc></Result>
        <Result><Desc>User Area Firmware Version</Desc></Result>
        <Result><Desc>EMV 2000 Controller Firmware Version</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCR78xxImageScannerTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** Test 1:Internal                                                    *** -->
<!-- *** Test 2: Test Imagescanner Communication                            *** -->
<!-- *** Test 10:Get Still Image                                            *** -->
<!-- *** Test 11:Get MetaData                                               *** -->
<!-- ************************************************************************* -->
<NCRTestDescr>
  <!--******************** Test 1: Internal ******************** -->
  <Test number="1" attended="no" destructive="no" exclusiveAccess="yes">
    <Desc>Internal</Desc>
    <Params separator=","/>
    <Results separator=",">
      <Result>
        <Desc>Status of the operation</Desc>
      </Result>
    </Results>
  </Test>

  <!--************* Test 2: Test imagescanner Communications ************* -->
  <Test number="2" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Test Device Communication</Desc>
    <Params separator=","/>
    <Results separator=",">
      <Result>
        <Desc>Status</Desc>
      </Result>
    </Results>
  </Test>

  <!--******************** Test 10:Get Still Image ****************** -->
  <Test number="10" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Get Still Image</Desc>
    <Params separator=",">
    </Params>

    <Results separator=",">
      <Result>
        <Desc>Status of test</Desc>
      </Result>
      <Result>
        <Desc>ImageHeight(in Pixels)</Desc>
      </Result>
      <Result>
        <Desc>ImageWidth(in Pixels)</Desc>
      </Result>
      <Result>
        <Desc>ImageLentgh(in Bytes)</Desc>
      </Result>
      <Result>
        <Desc>BitsPerPixel</Desc>
      </Result>
      <Result>
        <Desc>FrameType</Desc>
      </Result>
      <Result>
        <Desc>ImageType</Desc>
      </Result>
      <Result>
        <Desc>ImagePath</Desc>
      </Result>
    </Results>
  </Test>

  <!--******************** Test 11: Get MetaData ********************* -->
  <Test number="11" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Get Metadata</Desc>
    <Params separator=",">
    </Params>

    <Results separator=",">
      <Result>
        <Desc>Status of test</Desc>
      </Result>
      <Result>
        <Desc>MetaData Size(in Bytes)</Desc>
      </Result>
      <Result>
        <Desc>Metadata Bytes</Desc>
      </Result>
    </Results>
  </Test>
  
  <!--RPSUPOS-1541-->
  <!--******************** Test 12: Hardware Tallies ******************** -->
  <!--<Test number="12" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Hardware Tally</Desc>
    <Params separator=","/>
    <Results separator=",">
      <Result>
        <Desc>Status of the operation</Desc>
      </Result>
      <Result>
        <Desc>File Version:</Desc>
      </Result>
      <Result>
        <Desc>Build Date:</Desc>
      </Result>      
    </Results>
  </Test>-->

  <!--******************** Test 13: Init Scanwatch ******************** -->
  <Test number="13" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Init Scanwatch Process</Desc>
    <Params separator=","/>
    <Results separator=",">
      <Result>
        <Desc>Status of the operation</Desc>
      </Result>      
    </Results>
  </Test>

  <!--******************** Test 14: Reset Metadata Status ******************** -->
  <Test number="14" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Reset Metadata Status</Desc>
    <Params separator=","/>
    <Results separator=",">
      <Result>
        <Desc>Status of the operation</Desc>
      </Result>
    </Results>
  </Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRLineDisplayDiags.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in ANCRLineDisplayModel               *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>


<!--****** Test 0: Get CCL Data ****************************************** -->
<Test number="0" attended="no" destructive="no" exclusiveAccess="yes">
    <Desc>Get CCL Data</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Part Number</Desc></Result>
        <Result><Desc>Serial Number</Desc></Result>
        <Result><Desc>Firmware Version Number</Desc></Result>
    </Results>
</Test>

<!--****** Test 1: Display Generic Text ********************************** -->
<Test number="1" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Display Generic Text</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--****** Test 2: Display Specified Text ********************************** -->
<Test number="2" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Display Specified Text</Desc>
    <Params separator=",">
        <Param paramType="string" defaultValue="Text">
            <Desc>Text to display</Desc>
            <UIPrompt>Text to display</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--****** Test 3: Turn On All Display Elements **************************** -->
<Test number="3" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Turn On All Display Elements</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--****** Test 4: Display a Character ********* -->
<Test number="4" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Display a Character</Desc>
    <Params separator=",">
        <Param paramType="string" defaultValue="0041">
            <Desc>Character to display (in 4 hex digits)</Desc>
            <UIPrompt>Character to display (in 4 hex digits)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--****** Test 5: Start Display of All Characters in a Character Set ********* -->
<Test number="5" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Start Display of All Characters in a Character Set</Desc>
    <Params separator=",">
        <Param paramType="integer" defaultValue="0" isTimeout="no">
            <Desc>Character set to display (0 is current character set)</Desc>
            <UIPrompt>Character set (0 is current set)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="1000" isTimeout="no">
            <Desc>Delay between full displays of characters (in milliseconds)</Desc>
            <UIPrompt>Delay (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>


<!--****** Test 6: Stop Display of All Characters in a Character Set ********* -->
<Test number="6" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Stop Display of All Characters in a Character Set</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>
