=== JMARRUJO91/jazmyne/NCRTestDescr.dtd
<?xml encoding="UTF-8"?>

<!-- Revision: 1.0.0 NCRTestDescr.dtd -->

<!ELEMENT NCRTestDescr (Test+)>

<!ELEMENT Test (Desc, Params, Results)>
<!ATTLIST Test
          number CDATA #REQUIRED
          attended (yes | no) #REQUIRED
          destructive (yes | no) #REQUIRED
          exclusiveAccess (yes | no) #REQUIRED>
          
<!ELEMENT Desc (#PCDATA)>
          
<!ELEMENT Params (Param*)>
<!ATTLIST Params
          separator CDATA #REQUIRED>

<!ELEMENT Param (Desc, UIPrompt)>
<!ATTLIST Param
          paramType (string | integer) #REQUIRED
          defaultValue CDATA #IMPLIED
          isTimeout (yes | no) #IMPLIED>

<!ELEMENT UIPrompt (#PCDATA)>

<!ELEMENT Results (Result+)>
<!ATTLIST Results
          separator CDATA #REQUIRED>

<!ELEMENT Result (Desc)>

=== JMARRUJO91/jazmyne/NCR71xxPOSPrinterTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRPOSPrinterModel *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Begin insertion ******************** -->
<Test number="1" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Begin insertion</Desc>
    <Params separator=",">
        <Param paramType="integer" defaultValue="5000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: End insertion ******************** -->
<Test number="2" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>End insertion</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 3: Begin removal ******************** -->
<Test number="3" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Begin removal</Desc>
    <Params separator=",">
        <Param paramType="integer" defaultValue="5000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 4: End removal ******************** -->
<Test number="4" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>End removal</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 5: Flip slip ******************** -->
<Test number="5" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Flip slip</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--*************** Test 6: Print diagnostic string to receipt *************** -->
<Test number="6" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Print diagnostic string</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 7: Get last printer status ******************** -->
<Test number="7" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get last printer status</Desc>
    <Params separator="+"/>
    <Results separator="+">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Most recent printer status</Desc></Result>
    </Results>
</Test>

<!--***** Test 8: Print two sided thermal diagnostic string to receipt ***** -->
<Test number="8" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Print two sided thermal string</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!-- ************************************************************************* -->
<!-- *** These tests are specific to the NCR71xx printers                  *** -->
<!-- ************************************************************************* -->

<!--******************** Test 10: Get CCL data ******************** -->
<Test number="10" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get CCL data</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Class number</Desc></Result>
        <Result><Desc>Serial number</Desc></Result>
        <Result><Desc>Boot firmware version number</Desc></Result>
        <Result><Desc>Boot firmware part number</Desc></Result>
        <Result><Desc>Flash firmware version number</Desc></Result>
        <Result><Desc>Flash firmware part number</Desc></Result>
    </Results>
</Test>

<!--*************** RPSUPOS-1534 Support of the Diagnostic Print At Slip Station. *************** -->
<!--*************** Test 23: Print diagnostic string to receipt *************** -->
<Test number="23" attended="no" destructive="yes" exclusiveAccess="yes">
  <Desc>Print diagnostic string on slip station</Desc>
  <Params separator=","/>
  <Results separator=",">
    <Result>
      <Desc>Status of the operation</Desc>
    </Result>
  </Results>
</Test>
  <!--*************** End RPSUPOS-1534 *************** -->
</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRHardTotalsTestFile.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRHardTotalsModel *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Internal Checkhealth ******************** -->
<Test number="1" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Internal Checkhealth -- Validate Sumchecks</Desc>
    <Params separator=",">
      
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: External Checkhealth ******************** -->
<Test number="2" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>External Checkhealth -- Read/Write Test</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCR78xxScaleTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are specific to the NCR78xx Scales                    *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Internal ******************** -->
<Test number="1" attended="no" destructive="no" exclusiveAccess="yes">
    <Desc>Internal</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>


<!--******************** Test 11: ReadWeight ******************** -->
<Test number="11" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>ReadWeight</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="4000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Weight</Desc></Result>
    </Results>
</Test>

<!--******************** Test 12: LiveWeight ******************** -->
<Test number="12" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>LiveWeight</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="4000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Weight or Scale Status</Desc></Result>
    </Results>
</Test>
<!--******************** Test 13: Hardware Tallies ******************** -->
<Test number="13" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Hardware Tally</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>File Version:</Desc></Result>
        <Result><Desc>Build Date:</Desc></Result>
        <!--<Result><Desc>Scale Calibrated Count:</Desc></Result>-->
        <Result><Desc>Weight Units:</Desc></Result>
        <Result><Desc>Maximum Weight:</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRKeylockTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRKeylockModel.   *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Get Keylock Position ************* -->
<Test number="1" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get Current Keylock Position</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of Test</Desc></Result>
        <Result><Desc>Current Keylock Position</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: Hardware Detection *************** -->
<Test number="2" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Hardware Detection</Desc>
    <Params separator=",">
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of Hardware</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCR78xxScannerTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are specific to the NCR78xx Scanners                *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Internal ******************** -->
<Test number="1" attended="no" destructive="no" exclusiveAccess="yes">
    <Desc>Internal</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 11: ScanData ******************** -->
<Test number="11" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>ScanData</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="5000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>ScanData</Desc></Result>
        <Result><Desc>ScanDataLabel</Desc></Result>
        <Result><Desc>ScanDataType</Desc></Result>
        <Result><Desc>**Scan data may be truncated...</Desc></Result>
        <Result><Desc>**Commas in data shall appear as spaces.</Desc></Result>
    </Results>
</Test>

<!--******************** Test 12: Device Information ******************** -->
<Test number="12" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Device Information</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <!--Result><Desc>Firmware:</Desc></Result-->
        <Result><Desc>File Version:</Desc></Result>
        <Result><Desc>Build Date:</Desc></Result>
        <Result><Desc>Model:</Desc></Result>
        <Result><Desc>Serial Number:</Desc></Result>
        <Result><Desc>Firmware Part Number:</Desc></Result>
        <Result><Desc>Firmware Version:</Desc></Result>
        <Result><Desc>SubDevice Model:</Desc></Result>
        <Result><Desc>SubDevice Serial Number:</Desc></Result>
        <Result><Desc>SubDevice Firmware Part Number:</Desc></Result>
        <Result><Desc>SubDevice Firmware Version:</Desc></Result>
    </Results>
</Test>

<!--******************** Test 13: Hardware Tallies ******************** -->
<Test number="13" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Hardware Tally</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>File Version:</Desc></Result>
        <Result><Desc>Build Date:</Desc></Result>
        <Result><Desc>Age in seconds:</Desc></Result>
        <Result><Desc>System State:</Desc></Result>
        <Result><Desc>Successful Flash Updates:</Desc></Result>
    </Results>
</Test>
</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRToneIndicatorTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRToneIndicator.  *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!--******************** Test 1: Play Simple Tone ****************** -->
<Test number="1" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Play Simple Tone</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="500">
            <Desc>Pitch (in Hertz)</Desc>
            <UIPrompt>Pitch (in Hertz)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="500" isTimeout="yes">
            <Desc>Duration (in milliseconds)</Desc>
            <UIPrompt>Duration (in milliseconds)</UIPrompt>
        </Param>
        <Param paramType="integer"  defaultValue="100">
            <Desc>Volume (as a percentage of maximum volume)</Desc>
            <UIPrompt>Volume (as a percentage of maximum)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: Play Tone Sequence ******************** -->
<Test number="2" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Play Tone Sequence</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="500">
            <Desc>Pitch of first tone  (in Hertz)</Desc>
            <UIPrompt>Tone 1 Pitch (in Hertz)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="500"  isTimeout="yes">
            <Desc>Duration of first tone (in milliseconds)</Desc>
            <UIPrompt>Tone 1 Duration (in milliseconds)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="100">
            <Desc>Volume of first tone (as a percentage of maximum volume)</Desc>
            <UIPrompt>Tone 1 Volume (as a percentage)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="1000"  isTimeout="yes">
            <Desc>Pause between first and second tone (in milliseconds)</Desc>
            <UIPrompt>Intertone Wait (in milliseconds)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="500">
            <Desc>Pitch of second tone  (in Hertz)</Desc>
            <UIPrompt>Tone 2 Pitch (in Hertz)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="500"  isTimeout="yes">
            <Desc>Duration of second tone (in milliseconds)</Desc>
            <UIPrompt>Tone 2 Duration (in milliseconds)</UIPrompt>
        </Param>
        <Param paramType="integer" defaultValue="100">
            <Desc>Volume of second tone (as a percentage of maximum volume)</Desc>
            <UIPrompt>Tone 2 Volume (as a percentage)</UIPrompt>
        </Param>
        <!-- TAR 442738: Remove repeat count to prevent timeout errors -->
        <!--<Param paramType="integer" defaultValue="1">-->
        <!--    <Desc>Number of times to repeat the two tones</Desc>-->
        <!--    <UIPrompt>Repeat Count</UIPrompt>-->
        <!--</Param>-->
        <!--<Param paramType="integer"  defaultValue="0" isTimeout="yes">-->
        <!--    <Desc>Pause after second tone (in milliseconds) before sequence repeats</Desc>-->
        <!--    <UIPrompt>Intersequence Wait (in milliseconds)</UIPrompt>-->
        <!--</Param>-->
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
    </Results>
</Test>

<!--******************** Test 3: Play Default Tone ****************** -->
<Test number="3" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Play Default Tone</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of test</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRK5xxPOSPrinterTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<!-- ************************************************************************* -->
<!-- *** These tests are implemented in the base model ANCRPOSPrinterModel *** -->
<!-- *** Derived models may add additional tests                           *** -->
<!-- ************************************************************************* -->

<NCRTestDescr>

<!-- Note: Kiosk printers have no slip station -->
<!-- All slip specific tests have been removed -->


<!--*************** Test 6: Print diagnostic string to receipt *************** -->
<Test number="6" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Print diagnostic string</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 7: Get last printer status ******************** -->
<Test number="7" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get last printer status</Desc>
    <Params separator="+"/>
    <Results separator="+">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Most recent printer status</Desc></Result>
    </Results>
</Test>

<!--***** Test 8: Print two sided thermal diagnostic string to receipt ***** -->
<Test number="8" attended="no" destructive="yes" exclusiveAccess="yes">
    <Desc>Print two sided thermal string</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!-- ************************************************************************* -->
<!-- *** These tests are specific to the NCRK5xx (kiosk) printers          *** -->
<!-- ************************************************************************* -->

<!--******************** Test 10: Get CCL data ******************** -->
<Test number="10" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get CCL data</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Class number</Desc></Result>
        <Result><Desc>Serial number</Desc></Result>
        <Result><Desc>Boot firmware version number</Desc></Result>
        <Result><Desc>Boot firmware part number</Desc></Result>
        <Result><Desc>Flash firmware version number</Desc></Result>
        <Result><Desc>Flash firmware part number</Desc></Result>
    </Results>
</Test>

<!--******************** Test 11: Eject receipt ****** -->
<Test number="11" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Cut and eject receipt</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 12: Get most recent kiosk specific status ****** -->
<Test number="12" attended="no" destructive="no" exclusiveAccess="no">
    <Desc>Get last kiosk specific status</Desc>
    <Params separator="+"/>
    <Results separator="+">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>Most recent kiosk specific status</Desc></Result>
    </Results>
</Test>

</NCRTestDescr>

=== JMARRUJO91/jazmyne/NCRMICRTestFile.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE NCRTestDescr SYSTEM "NCRTestDescr.dtd">

<NCRTestDescr>

<!--******************** Test 1: Begin insertion ******************** -->
<Test number="1" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Begin insertion</Desc>
    <Params separator=",">
        <Param paramType="integer"  defaultValue="5000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 2: End insertion ******************** -->
<Test number="2" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>End insertion</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
        <Result><Desc>MICR data</Desc></Result>
        <Result><Desc>Account number</Desc></Result>
        <Result><Desc>Amount</Desc></Result>
        <Result><Desc>Bank number</Desc></Result>
        <Result><Desc>EPC data</Desc></Result>
        <Result><Desc>Serial number</Desc></Result>
        <Result><Desc>Transit number</Desc></Result>
        <Result><Desc>Check type</Desc></Result>
        <Result><Desc>Country code</Desc></Result>
    </Results>
</Test>

<!--******************** Test 3: Begin removal ******************** -->
<Test number="3" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>Begin removal</Desc>
    <Params separator=",">
        <Param paramType="integer" defaultValue="5000" isTimeout="yes">
            <Desc>Timeout (in milliseconds)</Desc>
            <UIPrompt>Timeout (in milliseconds)</UIPrompt>
        </Param>
    </Params>
    
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--******************** Test 4: End removal ******************** -->
<Test number="4" attended="yes" destructive="yes" exclusiveAccess="yes">
    <Desc>End removal</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Status of the operation</Desc></Result>
    </Results>
</Test>

<!--************* Test 5: Test Printer Communications ************* -->
<Test number="5" attended="no" destructive="no" exclusiveAccess="yes">
    <Desc>Test printer communications</Desc>
    <Params separator=","/>
    <Results separator=",">
        <Result><Desc>Communication status</Desc></Result>
    </Results>
</Test>


</NCRTestDescr>
